apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nacos.fullname" . }}-auth
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
type: Opaque
data:
  nacos-password: {{ .Values.auth.password | default "nacos" | b64enc | quote }}
