apiVersion: v1
kind: Service
metadata:
  name: {{ include "nacos.fullname" . }}
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "nacos.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nacos.fullname" . }}-headless
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "nacos.selectorLabels" . | nindent 4 }}
