// xarch-cloud-starter-gateway
plugins {
    id 'java-library'
}

dependencies {
    api project(':xarch-spring-boot-starter:xarch-core-spring-boot-starter')
    api project(':xarch-spring-boot-starter:xarch-resilience-spring-boot-starter')

    implementation 'org.springframework.cloud:spring-cloud-starter-gateway:4.1.0'
    implementation 'org.springframework.cloud:spring-cloud-starter-loadbalancer:4.1.0'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery:3.2.0'

    // Reactive support for Resilience4j circuit breaker
    implementation 'io.github.resilience4j:resilience4j-reactor:2.2.0'
    implementation 'io.github.resilience4j:resilience4j-spring-boot3:2.2.0'

    // Data Redis is required by the global rate limiter
    implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}
