plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':xarch-core-spring-boot-starter')
    implementation project(':xarch-db-spring-boot-starter')
    implementation project(':xarch-web-spring-boot-starter')
    implementation project(':xarch-cache-spring-boot-starter')

    runtimeOnly 'com.mysql:mysql-connector-j'
    runtimeOnly 'com.h2database:h2'
}

tasks.named('bootJar') {
    archiveFileName = 'app.jar'
}

springBoot {
    mainClass = 'com.xarch.example.XarchExampleApplication'
}