// xarch-mcp-knowledge
plugins {
    id 'java-library'
}

dependencies {
    implementation project(':xarch-core-spring-boot-starter')
    implementation 'org.springframework.boot:spring-boot-starter-web:3.4.0'
    implementation 'org.springframework.ai:spring-ai-ollama:1.0.0'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery:3.2.0'
    implementation 'org.apache.pdfbox:pdfbox:3.0.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
}

java {
    library {
        jvmVersion = 25
    }
}