{{- if .Values.routesConfigMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}-routes
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  routes.yaml: |
    {{- range .Values.routesConfigMap.routes }}
    - id: {{ .id }}
      uri: {{ .uri }}
      predicates:
        {{- range .predicates }}
        - {{ . }}
        {{- end }}
    {{- end }}
{{- end }}
