dependencies {
    api project(':xarch-spring-boot-starter:xarch-core-spring-boot-starter')
    implementation project(':xarch-spring-boot-starter:xarch-tracing-spring-boot-starter')

    compileOnly 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.springframework.boot:spring-boot-starter-validation'
    compileOnly 'org.springframework.boot:spring-boot-starter-aop'
    compileOnly 'org.springframework.boot:spring-boot-starter-websocket'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    api 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'
    api 'cn.dev33:sa-token-spring-boot3-starter:1.37.0'
    api 'io.swagger.core.v3:swagger-annotations'

    // Test dependencies
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testImplementation 'org.springframework.security:spring-security-test'
}

tasks.named('test') {
    useJUnitPlatform()
}