dependencies {
    api project(':xarch-spring-boot-starter:xarch-core-spring-boot-starter')

    compileOnly 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.springframework.boot:spring-boot-starter-validation'
    compileOnly 'org.springframework.boot:spring-boot-starter-aop'
    compileOnly 'org.springframework.boot:spring-boot-starter-websocket'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    api 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'
    api 'cn.dev33:sa-token-spring-boot3-starter:1.37.0'
    api 'io.swagger.core.v3:swagger-annotations'
}