dependencies {
    api 'org.projectlombok:lombok'

    compileOnly 'org.springframework.boot:spring-boot-starter'

    api 'com.fasterxml.jackson.core:jackson-databind'
    api 'cn.hutool:hutool-core:5.8.26'
    api 'cn.hutool:hutool-crypto:5.8.26'
    api 'cn.hutool:hutool-json:5.8.26'
    api 'org.slf4j:slf4j-api'
}