dependencies {
    api project(':xarch-spring-boot-starter:xarch-core-spring-boot-starter')

    compileOnly 'org.springframework.boot:spring-boot-starter'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    api 'org.springframework.boot:spring-boot-starter-jdbc'
    api 'com.mybatis-flex:mybatis-flex-spring-boot-starter:1.10.8'
    api 'com.github.pagehelper:pagehelper-spring-boot-starter:2.1.0'
    api 'com.mysql:mysql-connector-j'
    api 'org.postgresql:postgresql'
    api 'com.alibaba:druid-spring-boot-3-starter:1.2.23'
    api 'org.apache.commons:commons-lang3'

    // Test dependencies
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testRuntimeOnly 'org.h2database:h2'
}

tasks.named('test') {
    useJUnitPlatform()
}