dependencies {
    api project(':xarch-spring-boot-starter:xarch-core-spring-boot-starter')

    compileOnly 'org.springframework.boot:spring-boot-starter'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    api 'org.springframework.boot:spring-boot-starter-jdbc'
    api 'com.mybatis-flex:mybatis-flex-spring-boot-starter:1.10.8'
    api 'com.github.pagehelper:pagehelper-spring-boot-starter:2.1.0'
    api 'com.mysql:mysql-connector-j'
    api 'org.postgresql:postgresql'
    api 'com.alibaba:druid-spring-boot-3-starter:1.2.23'
    api 'org.apache.commons:commons-lang3'
}