{{- if .Values.limitRange.enabled -}}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "xarch.fullname" . }}-limits
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "xarch.labels" . | nindent 4 }}
spec:
  limits:
    - type: Container
      default:
        {{- toYaml .Values.limitRange.defaults | nindent 8 }}
      defaultRequest:
        {{- toYaml .Values.limitRange.requests | nindent 8 }}
{{- end }}
