apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "xarch.fullname" . }}-default-deny
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "xarch.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "xarch.fullname" . }}-allow-intra-namespace
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "xarch.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.namespace.name }}
  egress:
    - to:
        - podSelector: {}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.namespace.name }}
    # DNS
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
