{{- if .Values.resourceQuota.enabled -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "xarch.fullname" . }}-quota
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "xarch.labels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.resourceQuota.hard | nindent 4 }}
{{- end }}
