{{- if .Values.imagePullSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "xarch.labels" . | nindent 4 }}
  {{- with .Values.imagePullSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.imagePullSecret.registry .Values.imagePullSecret.username .Values.imagePullSecret.password .Values.imagePullSecret.email .Values.imagePullSecret.auth | b64enc | quote }}
{{- end }}
